// Rich detail content for each Biblical figure.
// Each entry: { bio, scriptures: [{ref, note}], moments: [string], theme, deeper: [{label,url}] }
// Scripture refs use SBL-style abbreviations; URLs auto-built via bgUrl().

export const bgUrl = (ref) =>
  `https://www.biblegateway.com/passage/?search=${encodeURIComponent(ref)}&version=ESV`

export const DETAILS = {
  jesus: {
    bio: "The eternal Son of God, second person of the Trinity, who became flesh and dwelt among us. Fully God and fully man, He lived a sinless life, was crucified for the sins of the world, rose bodily on the third day, and now reigns at the right hand of the Father. He is the long-promised Messiah, the fulfillment of every covenant from Eden onward.",
    scriptures: [
      { ref: "John 1:1-14", note: "The Word became flesh" },
      { ref: "Isaiah 53", note: "The Suffering Servant prophecy fulfilled" },
      { ref: "Philippians 2:5-11", note: "Humbled to death, exalted above every name" },
      { ref: "Hebrews 1:1-3", note: "Radiance of God's glory, exact imprint of His nature" },
      { ref: "Colossians 1:15-20", note: "All things created through Him and for Him" },
      { ref: "Revelation 5:9-12", note: "Worthy is the Lamb who was slain" },
    ],
    moments: ["Incarnation in Bethlehem", "Baptism by John", "40 days of temptation", "Sermon on the Mount", "Transfiguration", "Triumphal entry", "Last Supper", "Crucifixion at Calvary", "Resurrection on the third day", "Ascension"],
    theme: "Prophet, Priest, and King — the center and goal of all Scripture.",
    deeper: [
      { label: "Read the Gospel of John", url: bgUrl("John 1") },
      { label: "Hebrews 1 — Son above all", url: bgUrl("Hebrews 1") },
    ],
  },

  // ── Lineage / ancestors ─────────────────────────────────────────────
  adam: {
    bio: "The first man, formed by God from the dust and given dominion over creation. Adam's disobedience in Eden plunged humanity into sin and death, but he is also the federal head whose fall sets up the New Testament's portrait of Christ as the 'last Adam' who undoes the curse.",
    scriptures: [
      { ref: "Genesis 1:26-28", note: "Created in God's image, given dominion" },
      { ref: "Genesis 2:7", note: "Formed from dust, given the breath of life" },
      { ref: "Genesis 3", note: "The Fall and the first promise of redemption (3:15)" },
      { ref: "Romans 5:12-21", note: "One man's sin, one Man's righteousness" },
      { ref: "1 Corinthians 15:45", note: "Christ as the last Adam, a life-giving spirit" },
    ],
    moments: ["Created on day six", "Named every animal", "Eve formed from his side", "Disobeyed in eating the forbidden fruit", "Exiled from Eden"],
    theme: "Federal head of fallen humanity; type of Christ as the second Adam.",
    deeper: [{ label: "Genesis 1-3", url: bgUrl("Genesis 1-3") }],
  },
  noah: {
    bio: "The righteous man who walked with God in a generation marked by violence. God preserved Noah and his family through the global flood by means of an ark, then established a covenant with all flesh symbolized by the rainbow.",
    scriptures: [
      { ref: "Genesis 6:8-9", note: "Found favor in the eyes of the Lord" },
      { ref: "Genesis 7-9", note: "The Flood, the Ark, and the rainbow covenant" },
      { ref: "Hebrews 11:7", note: "By faith Noah constructed an ark" },
      { ref: "1 Peter 3:20-21", note: "The ark prefigures baptism / salvation" },
      { ref: "Matthew 24:37-39", note: "As the days of Noah, so the coming of the Son of Man" },
    ],
    moments: ["Built the ark", "Survived the flood", "Offered burnt offering after disembarking", "Received the rainbow covenant"],
    theme: "Salvation through judgment — the ark foreshadows Christ as our refuge.",
    deeper: [{ label: "Genesis 6-9", url: bgUrl("Genesis 6-9") }],
  },
  abraham: {
    bio: "Called from Ur of the Chaldeans, Abraham left everything to follow the promise of God: a land, a seed, and a blessing for all nations. Justified by faith, he is the father of all who believe — the patriarch through whom Messiah would come.",
    scriptures: [
      { ref: "Genesis 12:1-3", note: "The Abrahamic covenant — all families blessed" },
      { ref: "Genesis 15:6", note: "Believed God; counted as righteousness" },
      { ref: "Genesis 17", note: "Covenant of circumcision" },
      { ref: "Genesis 22", note: "Offered Isaac on Mount Moriah" },
      { ref: "Romans 4", note: "Paul's great exposition of Abraham's faith" },
      { ref: "Galatians 3:7-9", note: "Those of faith are sons of Abraham" },
    ],
    moments: ["Called from Ur", "Promised the land of Canaan", "Birth of Isaac in old age", "Bound Isaac on Moriah"],
    theme: "Father of faith; the covenant root from which Christ comes.",
    deeper: [{ label: "Genesis 12-25", url: bgUrl("Genesis 12-25") }],
  },
  sarah: {
    bio: "Wife of Abraham, mother of Isaac, and matriarch of the covenant line. After decades of barrenness, God opened her womb in old age — a foretaste of how God brings life out of impossibility.",
    scriptures: [
      { ref: "Genesis 17:15-16", note: "Renamed Sarah; she shall be a mother of nations" },
      { ref: "Genesis 18:9-15", note: "Laughed at the promise of a son" },
      { ref: "Genesis 21:1-7", note: "Birth of Isaac" },
      { ref: "Hebrews 11:11", note: "By faith Sarah received power to conceive" },
      { ref: "1 Peter 3:5-6", note: "Holy women of old hoped in God" },
    ],
    moments: ["Renamed by God", "Conceived Isaac at 90", "Buried in the cave of Machpelah"],
    theme: "Barrenness reversed by promise — God's pattern of life from the dead.",
    deeper: [{ label: "Genesis 18, 21", url: bgUrl("Genesis 18,21") }],
  },
  isaac: {
    bio: "The son of promise, miraculously born to Abraham and Sarah. His near-sacrifice on Moriah is the Old Testament's clearest type of the Father offering His only Son. He carried the covenant promise to the next generation.",
    scriptures: [
      { ref: "Genesis 21:1-7", note: "Birth of Isaac" },
      { ref: "Genesis 22", note: "The Aqedah — the binding of Isaac" },
      { ref: "Genesis 24", note: "Bride brought from afar (a type of the Church)" },
      { ref: "Hebrews 11:17-19", note: "Abraham reasoned God could raise him from the dead" },
      { ref: "Romans 9:7-9", note: "Through Isaac shall your offspring be named" },
    ],
    moments: ["Born to elderly parents", "Bound on Moriah", "Married Rebekah", "Blessed Jacob"],
    theme: "The beloved son carried the wood up the mountain — a foreshadow of Christ.",
    deeper: [{ label: "Genesis 22", url: bgUrl("Genesis 22") }],
  },
  rebekah: {
    bio: "Drawn from her family to marry Isaac, Rebekah became the mother of Jacob and Esau. She received the divine word that 'the older shall serve the younger,' shaping the trajectory of the covenant line.",
    scriptures: [
      { ref: "Genesis 24", note: "The bride at the well" },
      { ref: "Genesis 25:21-23", note: "Two nations in your womb" },
      { ref: "Genesis 27", note: "Helped Jacob secure the blessing" },
      { ref: "Romans 9:10-13", note: "Jacob I loved, Esau I hated — election" },
    ],
    moments: ["Met Abraham's servant at the well", "Conceived twins", "Helped redirect the blessing to Jacob"],
    theme: "Election runs through the covenant line; God's purpose stands.",
    deeper: [{ label: "Genesis 24-27", url: bgUrl("Genesis 24-27") }],
  },
  jacob: {
    bio: "Renamed Israel after wrestling with God, Jacob is the flawed patriarch through whom the twelve tribes descend. His life is a portrait of God's persistent grace pursuing a deceiver and turning him into a worshipper.",
    scriptures: [
      { ref: "Genesis 28:10-22", note: "Jacob's ladder at Bethel" },
      { ref: "Genesis 32:22-32", note: "Wrestled with God; renamed Israel" },
      { ref: "Genesis 49", note: "Final blessings — Judah's lion scepter" },
      { ref: "John 1:51", note: "Jesus is the true ladder between heaven and earth" },
    ],
    moments: ["Stole Esau's blessing", "Saw the ladder at Bethel", "Worked 14 years for Rachel", "Wrestled the angel", "Reunited with Joseph in Egypt"],
    theme: "Grace stronger than scheming — God transforms the supplanter.",
    deeper: [{ label: "Genesis 25-49", url: bgUrl("Genesis 25-49") }],
  },
  judah: {
    bio: "Fourth son of Jacob, ancestor of David and of Christ. From a flawed beginning he rose to become the leader of the brothers and the bearer of the kingly line — 'the lion of the tribe of Judah.'",
    scriptures: [
      { ref: "Genesis 38", note: "The complicated story with Tamar" },
      { ref: "Genesis 44:18-34", note: "Pleads for Benjamin — a Christ-like substitution" },
      { ref: "Genesis 49:8-12", note: "The scepter shall not depart from Judah" },
      { ref: "Revelation 5:5", note: "The Lion of the tribe of Judah has conquered" },
    ],
    moments: ["Sold Joseph into slavery", "Tamar incident", "Offered himself in place of Benjamin", "Received the kingly blessing"],
    theme: "From sinner to surety — the royal tribe through whom Messiah comes.",
    deeper: [{ label: "Genesis 38, 44, 49", url: bgUrl("Genesis 38,44,49") }],
  },
  tamar: {
    bio: "A Canaanite woman wronged by Judah's family, who took righteous (if shocking) initiative to secure the line of promise. She is one of four women named in Matthew's genealogy of Jesus.",
    scriptures: [
      { ref: "Genesis 38", note: "Her full story" },
      { ref: "Matthew 1:3", note: "Listed in the genealogy of Christ" },
      { ref: "Ruth 4:12", note: "May your house be like the house of Perez, whom Tamar bore to Judah" },
    ],
    moments: ["Widowed twice", "Denied levirate marriage by Judah", "Bore Perez and Zerah"],
    theme: "God writes the covenant story through unlikely women.",
    deeper: [{ label: "Genesis 38", url: bgUrl("Genesis 38") }],
  },
  joseph_ot: {
    bio: "Favored son of Jacob, sold by his brothers, falsely accused by Potiphar's wife, and exalted from the dungeon to second-in-command of Egypt. Joseph is the most thorough OT type of Christ: rejected by his own, suffering in silence, then exalted to save the very ones who betrayed him.",
    scriptures: [
      { ref: "Genesis 37", note: "Sold into slavery for silver" },
      { ref: "Genesis 39", note: "Faithful in Potiphar's house and in prison" },
      { ref: "Genesis 41", note: "From dungeon to Pharaoh's right hand" },
      { ref: "Genesis 45:5-8", note: "God sent me before you to preserve life" },
      { ref: "Genesis 50:20", note: "You meant evil; God meant it for good" },
    ],
    moments: ["Coat of many colors", "Sold for 20 pieces of silver", "Resisted Potiphar's wife", "Interpreted Pharaoh's dreams", "Saved his brothers in famine"],
    theme: "Betrayed → buried → exalted → saves: the most complete OT type of Christ.",
    deeper: [{ label: "Genesis 37-50", url: bgUrl("Genesis 37-50") }],
  },
  perez: {
    bio: "Son of Judah and Tamar, ancestor of Boaz and David. Mentioned in both major genealogies of Christ, he carries the line forward despite the brokenness surrounding his birth.",
    scriptures: [
      { ref: "Genesis 38:27-30", note: "Birth of Perez and Zerah" },
      { ref: "Ruth 4:18-22", note: "Genealogy from Perez to David" },
      { ref: "Matthew 1:3", note: "In the line of Christ" },
    ],
    moments: ["Born to Tamar", "Named in the genealogies"],
    theme: "Grace overflows the gaps — the line continues.",
    deeper: [{ label: "Ruth 4:18-22", url: bgUrl("Ruth 4:18-22") }],
  },
  rahab: {
    bio: "A Canaanite prostitute in Jericho who hid the Israelite spies and confessed faith in the God of Israel. Spared in the destruction of Jericho, she married Salmon and became great-great-grandmother of King David — and is named among the heroes of faith.",
    scriptures: [
      { ref: "Joshua 2", note: "Hid the spies; tied the scarlet cord" },
      { ref: "Joshua 6:22-25", note: "Saved when Jericho fell" },
      { ref: "Hebrews 11:31", note: "By faith Rahab the prostitute did not perish" },
      { ref: "James 2:25", note: "Justified by works that proved her faith" },
      { ref: "Matthew 1:5", note: "Named in the genealogy of Christ" },
    ],
    moments: ["Hid the spies", "Tied the scarlet cord in her window", "Spared in the fall of Jericho", "Married into the line of Messiah"],
    theme: "Outsider grafted in by faith; the scarlet cord recalls the blood of the Lamb.",
    deeper: [{ label: "Joshua 2, 6", url: bgUrl("Joshua 2,6") }],
  },
  salmon: {
    bio: "Husband of Rahab and father of Boaz; a quietly important link in the messianic line.",
    scriptures: [
      { ref: "Ruth 4:20-21", note: "Salmon fathered Boaz" },
      { ref: "Matthew 1:4-5", note: "In the line of Christ" },
    ],
    moments: ["Took Rahab as his wife", "Fathered Boaz"],
    theme: "The covenant line absorbs the redeemed Gentile.",
    deeper: [{ label: "Ruth 4", url: bgUrl("Ruth 4") }],
  },
  boaz: {
    bio: "A man of standing in Bethlehem who showed unprovoked kindness to Ruth the Moabitess and became her kinsman-redeemer. His name appears in every messianic genealogy.",
    scriptures: [
      { ref: "Ruth 2", note: "Welcomed Ruth in his fields" },
      { ref: "Ruth 3", note: "Threshing floor — request for redemption" },
      { ref: "Ruth 4", note: "Redeemed Naomi's land and married Ruth" },
      { ref: "Matthew 1:5", note: "Boaz the father of Obed by Ruth" },
    ],
    moments: ["Met Ruth gleaning", "Acted as goel (kinsman-redeemer)", "Married Ruth"],
    theme: "Kinsman-redeemer — points to Christ who buys back what we cannot.",
    deeper: [{ label: "Ruth 1-4", url: bgUrl("Ruth 1-4") }],
  },
  ruth: {
    bio: "A Moabite widow who clung to her mother-in-law Naomi and to Naomi's God: 'Your people shall be my people, and your God my God.' Redeemed by Boaz, she became great-grandmother of David and ancestor of Christ.",
    scriptures: [
      { ref: "Ruth 1:16-17", note: "Where you go, I will go" },
      { ref: "Ruth 2:12", note: "Boaz's blessing — under His wings" },
      { ref: "Ruth 4:13-17", note: "Birth of Obed; mother of David's father" },
      { ref: "Matthew 1:5", note: "In the genealogy of Christ" },
    ],
    moments: ["Left Moab for Bethlehem", "Gleaned in Boaz's field", "Asked for redemption at the threshing floor", "Married Boaz"],
    theme: "A foreigner of faith woven into the royal line.",
    deeper: [{ label: "The Book of Ruth", url: bgUrl("Ruth") }],
  },
  obed: {
    bio: "Son of Boaz and Ruth; father of Jesse; grandfather of King David — a quiet link in the line of promise.",
    scriptures: [
      { ref: "Ruth 4:13-22", note: "Birth and genealogy" },
      { ref: "Matthew 1:5", note: "In the line of Christ" },
    ],
    moments: ["Born to Boaz and Ruth", "Fathered Jesse"],
    theme: "Faithful generations carry the promise forward.",
    deeper: [{ label: "Ruth 4", url: bgUrl("Ruth 4") }],
  },
  jesse: {
    bio: "Father of King David. Isaiah prophesies that 'a shoot shall come from the stump of Jesse' — Messiah Himself. From his unremarkable household in Bethlehem comes Israel's greatest king and David's greater Son.",
    scriptures: [
      { ref: "1 Samuel 16:1-13", note: "Samuel anoints David at Jesse's house" },
      { ref: "Isaiah 11:1-10", note: "A shoot from the stump of Jesse" },
      { ref: "Romans 15:12", note: "Paul applies Isaiah 11 to Christ" },
    ],
    moments: ["Father of eight sons", "Hosted Samuel's anointing of David"],
    theme: "Bethlehem's stump becomes Messiah's root.",
    deeper: [{ label: "1 Samuel 16", url: bgUrl("1 Samuel 16") }],
  },
  david: {
    bio: "Shepherd, psalmist, warrior, and king — a man after God's own heart whose covenant from God promised an everlasting throne. David's failures are recorded honestly; his repentance and Christ-centered psalms shape the worship of the Church to this day.",
    scriptures: [
      { ref: "1 Samuel 16-17", note: "Anointed; defeats Goliath" },
      { ref: "2 Samuel 7", note: "The Davidic Covenant — your house forever" },
      { ref: "Psalm 22", note: "My God, why have you forsaken me — Christ on the cross" },
      { ref: "Psalm 51", note: "After Bathsheba — create in me a clean heart" },
      { ref: "Psalm 110", note: "The Lord said to my Lord" },
      { ref: "Matthew 1:1", note: "Jesus, son of David" },
    ],
    moments: ["Anointed by Samuel", "Defeated Goliath", "Spared Saul twice", "Established Jerusalem", "Sinned with Bathsheba and repented", "Received the eternal-throne covenant"],
    theme: "Type of Christ the King; the prophetic voice of the Psalter.",
    deeper: [{ label: "1 & 2 Samuel", url: bgUrl("1 Samuel 16-31") }, { label: "Psalm 22", url: bgUrl("Psalm 22") }],
  },
  bathsheba: {
    bio: "Wronged by David and bereaved of her first child, Bathsheba bore Solomon and stands in the line of Christ. Her story is a reminder that God's grace runs through the deepest brokenness.",
    scriptures: [
      { ref: "2 Samuel 11-12", note: "David's sin and Nathan's confrontation" },
      { ref: "1 Kings 1", note: "Secured Solomon's succession" },
      { ref: "Matthew 1:6", note: "Listed (as 'the wife of Uriah') in the genealogy of Christ" },
    ],
    moments: ["Taken by David", "Lost her first child", "Mother of Solomon", "Queen mother in Solomon's court"],
    theme: "Grace runs through wounds; the genealogy refuses to airbrush sin.",
    deeper: [{ label: "2 Samuel 11-12", url: bgUrl("2 Samuel 11-12") }],
  },
  solomon: {
    bio: "Son of David, builder of the Temple, and writer of much of the Bible's wisdom literature. His unparalleled wisdom and wealth foreshadow Messiah's reign of peace, even as his late-life idolatry warns of the limits of every earthly king.",
    scriptures: [
      { ref: "1 Kings 3:5-14", note: "Asked God for wisdom" },
      { ref: "1 Kings 8", note: "Dedication of the Temple" },
      { ref: "Proverbs 1:1-7", note: "The fear of the LORD is the beginning of knowledge" },
      { ref: "Ecclesiastes 12:13-14", note: "Fear God and keep His commandments" },
      { ref: "Matthew 12:42", note: "Something greater than Solomon is here" },
    ],
    moments: ["Crowned king", "Asked for wisdom", "Built the Temple", "Welcomed the Queen of Sheba", "Drifted into idolatry"],
    theme: "Wisdom and Temple-building point to Christ — but only Christ does not fall.",
    deeper: [{ label: "1 Kings 1-11", url: bgUrl("1 Kings 1-11") }],
  },

  // ── Prophets ────────────────────────────────────────────────────────
  elijah: {
    bio: "The fiery prophet who confronted Ahab and Jezebel, called fire down from heaven on Mount Carmel, and was taken up in a chariot of fire without seeing death. He appears with Moses on the Mount of Transfiguration, testifying to Jesus.",
    scriptures: [
      { ref: "1 Kings 17", note: "Ravens, widow of Zarephath, raised her son" },
      { ref: "1 Kings 18", note: "Showdown with Baal's prophets on Carmel" },
      { ref: "1 Kings 19", note: "Still small voice at Horeb" },
      { ref: "2 Kings 2:11", note: "Taken up in a whirlwind" },
      { ref: "Matthew 17:1-3", note: "Appears with Moses at the Transfiguration" },
      { ref: "Malachi 4:5-6", note: "Behold I send you Elijah" },
    ],
    moments: ["Confronted Ahab", "Fire on Carmel", "Fled to Horeb", "Taken to heaven alive"],
    theme: "Prophet of fire; herald of the Day of the Lord.",
    deeper: [{ label: "1 Kings 17-19", url: bgUrl("1 Kings 17-19") }],
  },
  elisha: {
    bio: "Successor to Elijah who received a double portion of his spirit. Elisha's miracles — feeding crowds, raising the dead, cleansing the leper — prefigure many of Jesus' own works.",
    scriptures: [
      { ref: "2 Kings 2:9-14", note: "Asks for and receives the double portion" },
      { ref: "2 Kings 4:1-7", note: "Widow's oil multiplied" },
      { ref: "2 Kings 4:32-37", note: "Raised the Shunammite's son" },
      { ref: "2 Kings 5", note: "Naaman the leper cleansed" },
      { ref: "Luke 4:27", note: "Jesus references Elisha and Naaman" },
    ],
    moments: ["Received Elijah's mantle", "Multiplied oil", "Raised the dead", "Healed Naaman"],
    theme: "Miracles of mercy that preview Messiah's ministry.",
    deeper: [{ label: "2 Kings 2-9", url: bgUrl("2 Kings 2-9") }],
  },
  isaiah: {
    bio: "Prophet to Judah whose book is sometimes called 'the fifth Gospel.' Isaiah's vision of the holy God in the Temple, the virgin-born Immanuel, the Suffering Servant of chapter 53, and the new heavens and new earth shaped Jewish messianic hope and the New Testament's portrait of Christ.",
    scriptures: [
      { ref: "Isaiah 6", note: "Holy, holy, holy — call of Isaiah" },
      { ref: "Isaiah 7:14", note: "The virgin shall conceive — Immanuel" },
      { ref: "Isaiah 9:6-7", note: "Unto us a child is born — Mighty God, Prince of Peace" },
      { ref: "Isaiah 40:3-5", note: "Prepare the way of the Lord" },
      { ref: "Isaiah 53", note: "Suffering Servant — pierced for our transgressions" },
      { ref: "Isaiah 61:1-3", note: "Spirit of the Lord upon Me — Jesus' inaugural sermon (Lk 4)" },
    ],
    moments: ["Saw the Lord high and lifted up", "Prophesied to Hezekiah", "Wrote of the Servant"],
    theme: "The Gospel before the Gospel.",
    deeper: [{ label: "Isaiah 53", url: bgUrl("Isaiah 53") }, { label: "Isaiah 61", url: bgUrl("Isaiah 61") }],
  },
  melchizedek: {
    bio: "Mysterious king-priest of Salem (Jerusalem) who blessed Abraham and received tithes from him. Hebrews holds him up as the type of Christ's eternal priesthood — without genealogy, without beginning of days.",
    scriptures: [
      { ref: "Genesis 14:18-20", note: "Brought out bread and wine, blessed Abraham" },
      { ref: "Psalm 110:4", note: "A priest forever after the order of Melchizedek" },
      { ref: "Hebrews 5-7", note: "The whole argument for Christ's superior priesthood" },
    ],
    moments: ["Blessed Abraham with bread and wine", "Received the tithe"],
    theme: "King-priest; eternal priesthood; type of the Lord Jesus.",
    deeper: [{ label: "Hebrews 7", url: bgUrl("Hebrews 7") }],
  },
  jeremiah: {
    bio: "The 'weeping prophet' who proclaimed Jerusalem's coming judgment and exile, but also the most beautiful promise of the Old Testament: a New Covenant written on hearts.",
    scriptures: [
      { ref: "Jeremiah 1:4-10", note: "Before I formed you in the womb I knew you" },
      { ref: "Jeremiah 31:31-34", note: "The New Covenant — I will write My law on their hearts" },
      { ref: "Lamentations 3:22-23", note: "His mercies are new every morning" },
      { ref: "Hebrews 8:8-12", note: "New Testament writers cite Jeremiah 31 as fulfilled in Christ" },
    ],
    moments: ["Called as a youth", "Wore the yoke of judgment", "Promised the New Covenant"],
    theme: "Tears for the city, hope in the New Covenant.",
    deeper: [{ label: "Jeremiah 31", url: bgUrl("Jeremiah 31") }],
  },
  micah: {
    bio: "An 8th-century prophet who declared that the Ruler of Israel would come from little Bethlehem — the verse the chief priests quoted to Herod when the magi arrived.",
    scriptures: [
      { ref: "Micah 5:2", note: "Bethlehem Ephrathah — from you shall come forth a Ruler" },
      { ref: "Micah 6:8", note: "Do justice, love kindness, walk humbly" },
      { ref: "Matthew 2:4-6", note: "Quoted at the magi's arrival" },
    ],
    moments: ["Bethlehem prophecy"],
    theme: "Bethlehem — the obscure place of God's appearing.",
    deeper: [{ label: "Micah 5", url: bgUrl("Micah 5") }],
  },
  zechariah_p: {
    bio: "Post-exile prophet whose oracles saturate the Passion narratives: the king on a donkey, the thirty pieces of silver, the pierced Shepherd, and the fountain opened for sin.",
    scriptures: [
      { ref: "Zechariah 9:9", note: "Your King comes — humble, on a donkey" },
      { ref: "Zechariah 11:12-13", note: "Thirty pieces of silver" },
      { ref: "Zechariah 12:10", note: "They will look on Him whom they pierced" },
      { ref: "Zechariah 13:7", note: "Strike the Shepherd; the sheep will be scattered" },
    ],
    moments: ["Visions of the night", "Messianic oracles"],
    theme: "The crucified King foreseen 500 years ahead.",
    deeper: [{ label: "Zechariah 9-14", url: bgUrl("Zechariah 9-14") }],
  },
  malachi: {
    bio: "The final voice of Old Testament prophecy. Malachi closes the canon with a promise: a messenger will prepare the way, and the sun of righteousness will rise with healing in His wings.",
    scriptures: [
      { ref: "Malachi 3:1", note: "Behold, I send My messenger before Me" },
      { ref: "Malachi 4:2", note: "The sun of righteousness shall rise with healing" },
      { ref: "Malachi 4:5-6", note: "I will send Elijah — applied to John the Baptist" },
    ],
    moments: ["Last word of OT prophecy"],
    theme: "The hinge between the Testaments.",
    deeper: [{ label: "Malachi 3-4", url: bgUrl("Malachi 3-4") }],
  },
  daniel: {
    bio: "Faithful in Babylonian exile, Daniel's visions reach further into the future than any other OT prophet. His 'Son of Man' coming on the clouds is the title Jesus claimed most often for Himself.",
    scriptures: [
      { ref: "Daniel 2:44-45", note: "A kingdom that will never be destroyed" },
      { ref: "Daniel 6", note: "The lions' den" },
      { ref: "Daniel 7:13-14", note: "One like a Son of Man — Jesus' favorite self-title" },
      { ref: "Daniel 9:24-27", note: "Seventy weeks — Messiah cut off" },
      { ref: "Matthew 26:64", note: "Jesus quotes Daniel 7 at His trial" },
    ],
    moments: ["Refused the king's food", "Interpreted dreams", "Lions' den", "Visions of empires and Messiah"],
    theme: "Son of Man enthroned — the kingdom that crushes all kingdoms.",
    deeper: [{ label: "Daniel 7", url: bgUrl("Daniel 7") }],
  },
  simeon: {
    bio: "A righteous and devout man to whom the Holy Spirit promised he would not see death until he had seen the Lord's Christ. Holding the infant Jesus in the Temple, he sang the Nunc Dimittis.",
    scriptures: [
      { ref: "Luke 2:25-35", note: "Now you let your servant depart in peace" },
    ],
    moments: ["Held the infant Jesus", "Prophesied a sword for Mary's soul"],
    theme: "A lifetime of waiting answered in one moment.",
    deeper: [{ label: "Luke 2:25-35", url: bgUrl("Luke 2:25-35") }],
  },
  anna: {
    bio: "An 84-year-old prophetess who never left the Temple, worshipping with fasting and prayer. She arrived as Simeon spoke and gave thanks, telling all who waited for redemption that Messiah had come.",
    scriptures: [
      { ref: "Luke 2:36-38", note: "Spoke of Him to all who were waiting" },
    ],
    moments: ["Recognized the infant Jesus", "Proclaimed Him in the Temple"],
    theme: "Prayer and prophecy meet in the courts of the Lord.",
    deeper: [{ label: "Luke 2:36-38", url: bgUrl("Luke 2:36-38") }],
  },

  // ── Family of Jesus ─────────────────────────────────────────────────
  zechariah_priest: {
    bio: "A righteous priest of the division of Abijah, and father of John the Baptist. Struck silent for unbelief at Gabriel's announcement, his tongue was loosed at John's naming and he prophesied the Benedictus.",
    scriptures: [
      { ref: "Luke 1:5-25", note: "Gabriel announces John's birth" },
      { ref: "Luke 1:67-79", note: "The Benedictus — Blessed be the Lord God of Israel" },
    ],
    moments: ["Struck mute", "Named his son John", "Prophesied at his son's birth"],
    theme: "Silenced doubt becomes louder praise.",
    deeper: [{ label: "Luke 1", url: bgUrl("Luke 1") }],
  },
  elizabeth: {
    bio: "Wife of Zechariah, relative of Mary, and mother of John the Baptist. Filled with the Holy Spirit, she was the first to call Mary the mother of her Lord.",
    scriptures: [
      { ref: "Luke 1:5-7", note: "Righteous before God, barren, advanced in years" },
      { ref: "Luke 1:39-45", note: "Filled with the Spirit; blessed are you among women" },
    ],
    moments: ["Conceived in old age", "Greeted Mary; the baby leapt in her womb"],
    theme: "Old-age conception echoes Sarah; faith recognizes the Lord.",
    deeper: [{ label: "Luke 1:39-56", url: bgUrl("Luke 1:39-56") }],
  },
  john_bap: {
    bio: "The forerunner of the Messiah, voice crying in the wilderness, last and greatest of the Old Testament-style prophets. He baptized Jesus, pointed his own disciples to Him, and was beheaded by Herod Antipas.",
    scriptures: [
      { ref: "Isaiah 40:3", note: "The voice in the wilderness — applied to John" },
      { ref: "Matthew 3", note: "Repent; the kingdom of heaven is at hand" },
      { ref: "Matthew 11:11", note: "None greater born of women than John" },
      { ref: "John 1:29", note: "Behold the Lamb of God who takes away the sin of the world!" },
      { ref: "John 3:30", note: "He must increase, but I must decrease" },
    ],
    moments: ["Born to elderly parents", "Camel-hair prophet", "Baptized Jesus", "Decreased so Christ could increase", "Beheaded by Herod"],
    theme: "The forerunner; the Lamb-pointer.",
    deeper: [{ label: "John 1:19-34", url: bgUrl("John 1:19-34") }],
  },
  joseph: {
    bio: "A righteous descendant of David, betrothed to Mary, and the legal earthly father of Jesus. Trusting an angel's word, he took Mary as his wife, named the child Jesus, and led the holy family to safety in Egypt.",
    scriptures: [
      { ref: "Matthew 1:18-25", note: "Joseph, son of David, do not fear" },
      { ref: "Matthew 2:13-15", note: "Flight to Egypt" },
      { ref: "Luke 2:1-7", note: "Went up to Bethlehem to register" },
      { ref: "Luke 2:41-52", note: "Pilgrimages to Jerusalem" },
    ],
    moments: ["Took Mary as his wife", "Named Jesus", "Fled to Egypt", "Raised Jesus in Nazareth"],
    theme: "Quiet, righteous obedience guards the line of the Son.",
    deeper: [{ label: "Matthew 1-2", url: bgUrl("Matthew 1-2") }],
  },
  mary: {
    bio: "The young woman of Nazareth who, by the overshadowing of the Holy Spirit, became the mother of the incarnate Son. Her Magnificat is the Old Testament's hopes set to song.",
    scriptures: [
      { ref: "Luke 1:26-38", note: "Behold, I am the servant of the Lord" },
      { ref: "Luke 1:46-55", note: "The Magnificat" },
      { ref: "John 2:1-11", note: "Cana — Do whatever He tells you" },
      { ref: "John 19:25-27", note: "Jesus entrusts her to John from the cross" },
      { ref: "Acts 1:14", note: "Praying with the disciples after the Ascension" },
    ],
    moments: ["Annunciation", "Visit to Elizabeth", "Birth in Bethlehem", "Lost-and-found Jesus at the Temple", "Cana", "At the cross"],
    theme: "Faithful 'yes' that opens the door to Incarnation.",
    deeper: [{ label: "Luke 1", url: bgUrl("Luke 1") }],
  },
  james_br: {
    bio: "The Lord's half-brother, who did not believe during Jesus' earthly ministry but became a pillar of the Jerusalem church after a personal resurrection appearance. He authored the Epistle of James.",
    scriptures: [
      { ref: "Mark 6:3", note: "Listed as Jesus' brother" },
      { ref: "John 7:5", note: "His brothers did not believe in Him" },
      { ref: "1 Corinthians 15:7", note: "Then He appeared to James" },
      { ref: "Acts 15:13-21", note: "Led the Jerusalem Council" },
      { ref: "Galatians 1:19", note: "James the Lord's brother" },
      { ref: "James 1:1", note: "James, a servant of God and of the Lord Jesus" },
    ],
    moments: ["Skeptical brother", "Resurrection appearance", "Pillar of Jerusalem", "Wrote his epistle", "Martyred c. AD 62"],
    theme: "Unbelief turned worship; family of the Lord and shepherd of the church.",
    deeper: [{ label: "James 1", url: bgUrl("James 1") }],
  },
  jude_br: {
    bio: "Brother of James and half-brother of Jesus. Author of the short epistle warning against false teachers and calling believers to contend for the faith.",
    scriptures: [
      { ref: "Mark 6:3", note: "Listed as Jesus' brother (Judas)" },
      { ref: "Jude 1", note: "Jude, brother of James" },
      { ref: "Jude 24-25", note: "Now to Him who is able to keep you from stumbling" },
    ],
    moments: ["Wrote the Epistle of Jude"],
    theme: "Contend for the faith once delivered to the saints.",
    deeper: [{ label: "Jude", url: bgUrl("Jude") }],
  },

  // ── Inner circle ────────────────────────────────────────────────────
  peter: {
    bio: "Simon, son of Jonah, renamed Cephas/Peter ('Rock') by Jesus. Bold and impulsive, he confessed Christ as the Son of the living God, denied Him three times, was restored, preached at Pentecost, opened the door of faith to the Gentiles, and was eventually crucified — by tradition, upside down.",
    scriptures: [
      { ref: "Matthew 16:13-19", note: "You are the Christ — keys of the kingdom" },
      { ref: "Luke 22:31-34, 54-62", note: "Denial foretold and fulfilled" },
      { ref: "John 21:15-19", note: "Restoration — feed My sheep" },
      { ref: "Acts 2", note: "Pentecost sermon — 3,000 added" },
      { ref: "Acts 10", note: "Cornelius — Gentiles welcomed" },
      { ref: "1 Peter 1:3-9", note: "A living hope through the resurrection" },
    ],
    moments: ["Walked on water", "Confessed Christ at Caesarea Philippi", "Denied Him in the courtyard", "Preached Pentecost", "Vision on the rooftop", "Wrote two epistles"],
    theme: "From boasting to brokenness to bold witness.",
    deeper: [{ label: "John 21", url: bgUrl("John 21") }, { label: "1 Peter 1", url: bgUrl("1 Peter 1") }],
  },
  john_ap: {
    bio: "Son of Zebedee, brother of James, and 'the disciple whom Jesus loved.' Author of the Fourth Gospel, three epistles, and Revelation. Cared for Jesus' mother after the cross. Tradition places his death in Ephesus.",
    scriptures: [
      { ref: "John 13:23", note: "Reclining at the Last Supper" },
      { ref: "John 19:26-27", note: "Behold your mother" },
      { ref: "John 20:1-9", note: "Saw and believed at the empty tomb" },
      { ref: "1 John 1:1-4", note: "That which we have heard, seen, touched" },
      { ref: "Revelation 1:9-18", note: "On Patmos — saw the glorified Christ" },
    ],
    moments: ["Called from the nets", "Beloved disciple at the Supper", "At the cross", "First into the empty tomb", "Exiled to Patmos"],
    theme: "The disciple of love who saw the glory.",
    deeper: [{ label: "Gospel of John", url: bgUrl("John 1") }],
  },
  james_z: {
    bio: "Son of Zebedee and brother of John, called a 'son of thunder.' Part of the inner three with Peter and John. The first apostle martyred — beheaded by Herod Agrippa.",
    scriptures: [
      { ref: "Mark 3:17", note: "Boanerges — sons of thunder" },
      { ref: "Mark 10:35-45", note: "Asked for thrones; offered the cup of suffering" },
      { ref: "Acts 12:1-2", note: "Killed with the sword by Herod" },
    ],
    moments: ["Inner-circle witness of the Transfiguration", "Asked for greatness; received martyrdom"],
    theme: "First to drink the cup; the cost of the kingdom.",
    deeper: [{ label: "Acts 12", url: bgUrl("Acts 12") }],
  },

  // ── The rest of the Twelve ──────────────────────────────────────────
  andrew: {
    bio: "Simon Peter's brother, originally a disciple of John the Baptist. The first to follow Jesus and the first to bring someone else to Him — his brother. Tradition has him martyred on an X-shaped cross.",
    scriptures: [
      { ref: "John 1:35-42", note: "Followed Jesus; brought Peter" },
      { ref: "John 6:8-9", note: "Brought the boy with the loaves" },
      { ref: "John 12:20-22", note: "Brought the Greeks who wished to see Jesus" },
    ],
    moments: ["First-called", "Always bringing someone to Jesus"],
    theme: "The bringer.",
    deeper: [{ label: "John 1:35-42", url: bgUrl("John 1:35-42") }],
  },
  matthew: {
    bio: "Also called Levi, a tax collector despised by his fellow Jews. Jesus called him from his tax booth; he hosted a great feast for sinners and later wrote the first Gospel, the most Jewish of the four.",
    scriptures: [
      { ref: "Matthew 9:9-13", note: "Follow Me — and he rose and followed" },
      { ref: "Mark 2:13-17", note: "I came not to call the righteous but sinners" },
      { ref: "Matthew 1", note: "Wrote the genealogy of Jesus the Messiah" },
    ],
    moments: ["Left the tax booth", "Hosted a sinners' feast", "Wrote the Gospel of Matthew"],
    theme: "The tax man writes the King's genealogy.",
    deeper: [{ label: "Matthew 9", url: bgUrl("Matthew 9") }],
  },
  thomas: {
    bio: "Twin (Didymus). Brave enough to say 'let us go and die with Him,' yet famously skeptical until he saw the risen Jesus and confessed, 'My Lord and my God!' Tradition places his missionary work in India.",
    scriptures: [
      { ref: "John 11:16", note: "Let us also go, that we may die with Him" },
      { ref: "John 14:5-6", note: "Lord, we don't know the way — I am the way" },
      { ref: "John 20:24-29", note: "My Lord and my God!" },
    ],
    moments: ["Loyal to death", "Doubted; then worshipped"],
    theme: "Honest doubt that ends in worship.",
    deeper: [{ label: "John 20:24-29", url: bgUrl("John 20:24-29") }],
  },
  philip: {
    bio: "From Bethsaida; called early and immediately brought Nathanael. He invited a curious man to 'come and see,' and Jesus tested his faith with the loaves.",
    scriptures: [
      { ref: "John 1:43-46", note: "Come and see" },
      { ref: "John 6:5-7", note: "Tested with the feeding of the 5,000" },
      { ref: "John 14:8-9", note: "Show us the Father — whoever has seen Me has seen the Father" },
    ],
    moments: ["Brought Nathanael", "Asked to see the Father"],
    theme: "Invitation: come and see.",
    deeper: [{ label: "John 14:1-14", url: bgUrl("John 14:1-14") }],
  },
  bartholomew: {
    bio: "Likely the same as Nathanael, a man Jesus called 'truly an Israelite, in whom there is no deceit.' Skeptical at first ('Can anything good come out of Nazareth?'), he became a worshipper.",
    scriptures: [
      { ref: "John 1:43-51", note: "Behold, an Israelite indeed" },
      { ref: "John 21:2", note: "Among the seven by the Sea of Tiberias" },
    ],
    moments: ["Met by Jesus under the fig tree", "Confessed Him as Son of God and King of Israel"],
    theme: "Open-hearted; honest before Jesus.",
    deeper: [{ label: "John 1:43-51", url: bgUrl("John 1:43-51") }],
  },
  simon_z: {
    bio: "Called 'the Zealot' — likely tied to the political movement seeking Israel's liberation. Jesus called both a tax collector (Matthew) and a Zealot (Simon) into the same Twelve, a sign of the kingdom that crosses every line.",
    scriptures: [
      { ref: "Luke 6:15", note: "Simon who was called the Zealot" },
      { ref: "Acts 1:13", note: "Among the apostles after the Ascension" },
    ],
    moments: ["Called from a militant party"],
    theme: "Christ unites enemies in one fellowship.",
    deeper: [{ label: "Luke 6:12-16", url: bgUrl("Luke 6:12-16") }],
  },
  thaddaeus: {
    bio: "Also called Judas son of James (Lebbaeus / Thaddaeus). Asked at the Last Supper why Jesus would manifest Himself to the disciples and not to the world.",
    scriptures: [
      { ref: "John 14:22-23", note: "Lord, why to us and not to the world?" },
      { ref: "Luke 6:16", note: "Listed among the Twelve" },
    ],
    moments: ["Asked at the Last Supper about manifestation"],
    theme: "Hidden faithfulness in the Twelve.",
    deeper: [{ label: "John 14:22-31", url: bgUrl("John 14:22-31") }],
  },
  james_a: {
    bio: "James the son of Alphaeus, sometimes called 'James the Less.' Little is recorded of him in the Gospels — yet he was named, called, and sent.",
    scriptures: [
      { ref: "Mark 3:18", note: "Listed among the Twelve" },
      { ref: "Acts 1:13", note: "Present after the Resurrection" },
    ],
    moments: ["Called and named"],
    theme: "Faithful obscurity is still faithfulness.",
    deeper: [{ label: "Mark 3:13-19", url: bgUrl("Mark 3:13-19") }],
  },
  judas: {
    bio: "Judas Iscariot, treasurer of the Twelve, who betrayed Jesus for thirty pieces of silver. Filled with remorse, not repentance, he hanged himself. His story is the Bible's gravest warning that nearness to Christ is not the same as belonging to Christ.",
    scriptures: [
      { ref: "John 12:4-6", note: "A thief — kept the money bag" },
      { ref: "Matthew 26:14-16", note: "Sold for thirty pieces of silver — Zech 11:12-13" },
      { ref: "John 13:21-30", note: "It was night" },
      { ref: "Matthew 27:3-10", note: "Threw the silver into the temple; hanged himself" },
    ],
    moments: ["Kept the moneybag", "Identified Jesus with a kiss", "Despaired and died"],
    theme: "Solemn warning: proximity is not salvation.",
    deeper: [{ label: "John 13", url: bgUrl("John 13") }],
  },

  // ── Women / Bethany ─────────────────────────────────────────────────
  mary_mag: {
    bio: "A woman from whom Jesus cast out seven demons. She supported His ministry, stood by His cross, watched His burial, and was the first to see Him risen — sent to tell the apostles, the 'apostle to the apostles.'",
    scriptures: [
      { ref: "Luke 8:1-3", note: "Seven demons cast out; supported the ministry" },
      { ref: "John 19:25", note: "Standing near the cross" },
      { ref: "John 20:1-18", note: "First witness of the resurrection — Rabboni!" },
    ],
    moments: ["Delivered from seven demons", "Stood at the cross", "Saw the empty tomb", "First saw the risen Lord"],
    theme: "First witness of the resurrection.",
    deeper: [{ label: "John 20:1-18", url: bgUrl("John 20:1-18") }],
  },
  martha: {
    bio: "Sister of Mary and Lazarus in Bethany. Famous for her serving and famous for the 'one thing necessary,' she made one of the great confessions of faith: 'You are the Christ, the Son of God.'",
    scriptures: [
      { ref: "Luke 10:38-42", note: "One thing is necessary" },
      { ref: "John 11:21-27", note: "I am the resurrection and the life" },
      { ref: "John 12:2", note: "Served at the supper" },
    ],
    moments: ["Welcomed Jesus", "Confessed Him at Lazarus' tomb", "Served the resurrection-supper"],
    theme: "Service that worships.",
    deeper: [{ label: "John 11", url: bgUrl("John 11") }],
  },
  mary_beth: {
    bio: "Mary of Bethany — the woman of one focus, who sat at Jesus' feet, anointed Him with costly perfume, and was commended by Him for choosing the good portion.",
    scriptures: [
      { ref: "Luke 10:38-42", note: "Sat at Jesus' feet" },
      { ref: "John 11:32-35", note: "If You had been here" },
      { ref: "John 12:1-8", note: "Anointed Jesus for burial" },
    ],
    moments: ["Sat at His feet", "Wept at the tomb", "Anointed Him with nard"],
    theme: "Worship that sees the cross coming.",
    deeper: [{ label: "John 12:1-8", url: bgUrl("John 12:1-8") }],
  },
  lazarus: {
    bio: "The friend Jesus loved, raised from the dead after four days in the tomb — the climactic sign before the cross. After his resurrection, the chief priests sought to kill him too because many believed because of him.",
    scriptures: [
      { ref: "John 11", note: "Lazarus, come out!" },
      { ref: "John 12:9-11", note: "The chief priests plotted to kill Lazarus also" },
    ],
    moments: ["Died, four days in the tomb", "Raised at Jesus' word", "Living testimony"],
    theme: "Living proof of resurrection power.",
    deeper: [{ label: "John 11", url: bgUrl("John 11") }],
  },

  // ── Early church ────────────────────────────────────────────────────
  paul: {
    bio: "Saul of Tarsus, Pharisee and persecutor of the church, struck down by the risen Christ on the road to Damascus. He became the apostle to the Gentiles, planted churches across the Roman world, wrote thirteen New Testament letters, and was martyred in Rome under Nero.",
    scriptures: [
      { ref: "Acts 9", note: "Damascus road conversion" },
      { ref: "Acts 13-28", note: "Three missionary journeys and Roman trial" },
      { ref: "Romans 1:16-17", note: "I am not ashamed of the gospel" },
      { ref: "1 Corinthians 15", note: "The resurrection chapter" },
      { ref: "Galatians 2:20", note: "Crucified with Christ — Christ lives in me" },
      { ref: "Philippians 3:7-14", note: "I count everything as loss" },
      { ref: "2 Timothy 4:7-8", note: "I have fought the good fight" },
    ],
    moments: ["Persecuted the church", "Met Christ on the Damascus road", "Three missionary journeys", "Imprisoned in Rome", "Wrote half the New Testament"],
    theme: "Chief of sinners turned chief witness of grace.",
    deeper: [{ label: "Acts 9", url: bgUrl("Acts 9") }, { label: "Romans", url: bgUrl("Romans 1") }],
  },
  stephen: {
    bio: "One of the seven deacons of the Jerusalem church, full of grace and power. The first martyr — stoned outside the city gates, praying for his killers, with the young Saul of Tarsus looking on.",
    scriptures: [
      { ref: "Acts 6:1-7", note: "Chosen as one of the seven" },
      { ref: "Acts 7", note: "His sermon — the long Old Testament arc" },
      { ref: "Acts 7:54-60", note: "Stoned; saw Jesus standing at the right hand of God" },
    ],
    moments: ["Preached Christ from the whole Old Testament", "First Christian martyr", "Forgave his killers"],
    theme: "Christ standing to receive His martyr.",
    deeper: [{ label: "Acts 7", url: bgUrl("Acts 7") }],
  },
  barnabas: {
    bio: "'Son of encouragement.' He vouched for the converted Saul to a fearful Jerusalem church and partnered with Paul on the first missionary journey. Later he and Paul parted over John Mark — and Barnabas restored Mark, who would write the Gospel of Mark.",
    scriptures: [
      { ref: "Acts 4:36-37", note: "Sold a field; laid the proceeds at the apostles' feet" },
      { ref: "Acts 9:26-27", note: "Brought Saul to the apostles" },
      { ref: "Acts 11:22-26", note: "Sent to Antioch — full of the Spirit and faith" },
      { ref: "Acts 13-15", note: "First missionary journey; split over John Mark" },
    ],
    moments: ["Vouched for Saul", "Sent to Antioch", "Mentored John Mark"],
    theme: "Encouragement that builds the church.",
    deeper: [{ label: "Acts 11", url: bgUrl("Acts 11") }],
  },
  nicodemus: {
    bio: "A ruler of the Jews and Pharisee who came to Jesus by night, heard the words 'you must be born again,' and gradually moved from secret seeker to public disciple — helping Joseph of Arimathea bury Him.",
    scriptures: [
      { ref: "John 3:1-21", note: "You must be born again — for God so loved the world" },
      { ref: "John 7:50-52", note: "Defended Jesus before the Sanhedrin" },
      { ref: "John 19:39-42", note: "Brought myrrh and aloes for Jesus' burial" },
    ],
    moments: ["Came by night", "Defended Jesus", "Helped bury Him"],
    theme: "Slow, costly, real conversion.",
    deeper: [{ label: "John 3:1-21", url: bgUrl("John 3:1-21") }],
  },
  joseph_ar: {
    bio: "A wealthy member of the Sanhedrin who had not consented to Jesus' condemnation. He boldly asked Pilate for the body of Jesus and laid Him in his own new tomb — fulfilling Isaiah 53:9.",
    scriptures: [
      { ref: "Matthew 27:57-60", note: "Wrapped Jesus in linen, laid Him in his own tomb" },
      { ref: "Mark 15:42-46", note: "A respected member of the council, looking for the kingdom" },
      { ref: "Isaiah 53:9", note: "With a rich man in His death" },
    ],
    moments: ["Asked Pilate for the body", "Buried Jesus in his new tomb"],
    theme: "Quiet courage at the most public cross.",
    deeper: [{ label: "Matthew 27:57-66", url: bgUrl("Matthew 27:57-66") }],
  },

  // ── Opponents ──────────────────────────────────────────────────────
  satan: {
    bio: "The adversary, originally a created angel who fell through pride. He tempted Jesus in the wilderness, entered Judas, and stands as accuser of the brethren — yet his head was crushed at the cross and his final defeat is sure.",
    scriptures: [
      { ref: "Genesis 3:1-15", note: "The serpent — the protoevangelium" },
      { ref: "Job 1-2", note: "The accuser before God's throne" },
      { ref: "Matthew 4:1-11", note: "Tempted Jesus in the wilderness" },
      { ref: "John 12:31", note: "Now will the ruler of this world be cast out" },
      { ref: "Revelation 12:9-11", note: "Conquered by the blood of the Lamb" },
      { ref: "Revelation 20:10", note: "Final defeat in the lake of fire" },
    ],
    moments: ["Eden", "Wilderness temptation", "Cross — head crushed", "Final defeat"],
    theme: "Defeated foe; crushed under the heel of the Seed of the woman.",
    deeper: [{ label: "Matthew 4:1-11", url: bgUrl("Matthew 4:1-11") }],
  },
  herod_g: {
    bio: "Herod the Great, an Idumean client-king of Rome who ruled Judea at Christ's birth. Threatened by the magi's news, he ordered the slaughter of the boys of Bethlehem.",
    scriptures: [
      { ref: "Matthew 2:1-18", note: "The magi, the slaughter, and the flight to Egypt" },
      { ref: "Jeremiah 31:15", note: "Rachel weeping for her children — fulfilled" },
    ],
    moments: ["Slaughter of the innocents"],
    theme: "Earthly thrones tremble at the true King.",
    deeper: [{ label: "Matthew 2", url: bgUrl("Matthew 2") }],
  },
  pilate: {
    bio: "The Roman prefect of Judea who tried Jesus, declared Him innocent three times, and yet handed Him over to be crucified. His question 'What is truth?' echoes through the centuries.",
    scriptures: [
      { ref: "John 18:28-19:22", note: "What is truth? — Behold the Man — Crucify Him" },
      { ref: "Matthew 27:24", note: "Washed his hands" },
      { ref: "1 Timothy 6:13", note: "Confessed before Pontius Pilate the good confession" },
    ],
    moments: ["Three innocence verdicts", "Sentenced Jesus to death", "Wrote 'King of the Jews'"],
    theme: "Cowardice cannot wash itself.",
    deeper: [{ label: "John 18:28-19:22", url: bgUrl("John 18:28-19:22") }],
  },
  caiaphas: {
    bio: "The high priest who presided over Jesus' trial. He prophesied unwittingly that 'one man should die for the people' — the very heart of the gospel he tried to silence.",
    scriptures: [
      { ref: "John 11:49-52", note: "It is better that one man die — prophesied unwittingly" },
      { ref: "Matthew 26:57-66", note: "Tore his robes — He has spoken blasphemy!" },
    ],
    moments: ["Plotted Jesus' death", "Tried Him before the Sanhedrin"],
    theme: "Even an enemy's mouth declares the gospel.",
    deeper: [{ label: "John 11:45-57", url: bgUrl("John 11:45-57") }],
  },
}
